### ISSUE TITLE
ff-asn-group-element use id for selected and unselected state

### ISSUE THREAD

**Issue by mekedron** [FACT-Finder-Web-Components/ff-web-components#11]
You can check the [demo](https://search-web-components.fact-finder.de/demos/current/ff-asn/?query=trousers&channel=bergfreunde-co-uk&sid=RJmTakRkR6VhIXtTKfa68xiAnMJNtG)
Just put `document.querySelectorAll('[id=selected], [id=unselected]').length` into the console, and see there are many elements with same ids, what is wrong by the html specification

**Comment by toarm** [comment]
That is actually an side effect caused by the polyfill. This issue will dissapear with our next major release. 
The elements with the **id** selected/unselected are part of that components Shadow Dom and therefore not subject to that naming collision. 
Our next major release will be available pretty soon (q4 2018)
