### ISSUE TITLE
Selecting filters without immediate application to results

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#24]
I hope it is OK to use this channel to ask general questions about the FF web components?

My UX colleauges have a requirement: **In a mobile context the user should be able to select all filters he wants and apply the selected filters together in one request by hitting a button.** 

It seems to me that the default behaviour of FACT-Finder is, that after selecting a filter, the results _and_ filters are updated, so that only possible additional filters are displayed anymore.

So, following the requested use case the chances might be high that the user selects combinations that ends in an empty result.

However, is there the possibility to configure the web components to behave exactly like described?

Thanks,
Markus

**Comment by ghost** [comment]
> I hope it is OK to use this channel to ask general questions about the FF web components?

Each idea / question is always very welcome. In the 'worst case' we will just answer with a link to the related documentation part ;-)

> So, following the requested use case the chances might be high that the user selects combinations that ends in an empty result.

That is the exact reason. From a selling point of view no results are the worst case scenario. 

However I see that it can be annoying on mobile context to select a filter, wait for the result, select another filter...

We will need to discuss, if we want to add this as a feature. If not I am very confident, that we can provide a custom code snippet [in our demo project](https://github.com/FACT-Finder-Web-Components/demos), how to customize this behaviour by yourself through provided interfaces like `factfinder.communication.ResultDispatcher.addCallback`.

I created internal ticket FFWEB-1326 for that. We will update this issue here accordingly.

**Comment by toarm** [comment]
Hi @mwinkelm 

> However, is there the possibility to configure the web components to behave exactly like described?
You might be able to prevent all `event.type === "filter"` in an `addBeforeDispatchingCallback ` https://web-components.fact-finder.de/api/3.x/core-event-aggregator

deleting the `type` property in the callback will prevent any further action. 

I'm pretty sure we could provide a code snippet in the near future but we are pretty busy atm. Could take a while.

**Comment by mwinkelm** [comment]
Hi @toarm 

after an internal discussion about this topic we all agree that the current behaviour is good. On mobile we go for a button in the filter overlay that says: "See x results" instead of an "apply filter" function.

Thanks for pointing me to `addBeforeDispatchingCallback`, because I havn't read the docs carefully enough yet. No need for a code snippet!

Thanks a lot for your advice!
