### ISSUE TITLE
Feature request: ff-asn-remove-all-filter keep-additional-params

### ISSUE THREAD

**Issue by Taxel** [FACT-Finder-Web-Components/ff-web-components#46]
Hey there,

the `ff-asn-filter` currently supports `keep-category-path`, which works fine on category pages.
I am currently building a "Our Brands" page with factfinder results for each brand. This was quickly implemented by passing `add-params="navigation=true,filterManufacturer=MyURLEncodedManufacturer"` to `ff-communication`.
The problem is, that the `ff-asn-remove-all-filter` can now reset the brand, which is obviously not desirable in this case.

I propose to add an option that simply keeps the `add-params` in the communication object the same and resets everything else. Ideally, the `ff-asn-remove-all-filter` would also only be visible if filters in addition to the `add-params` are selected, not always when a filter is set, which is also a minor problem with `keep-category-path`.

**Comment by omikron-fp** [comment]
Hi @Taxel,
After some internal debate, we concluded that your proposal would be a useful addition to WebComponents.

At this point in time there is no consensus yet on how exactly this feature would be implemented. Due to the involvement of `add-params`, there is a chance of causing a chain of side-effects. Therefore, we must create a thorough concept first.
Unfortunately, it's difficult to estimate how long this will take but we are ourselves eager to bring this feature to life soon.

**Comment by omikron-fp** [comment]
Hi @Taxel,
We are currently working on a task that should solve your described issue.
At the moment we are thinking to introduce a new attribute on `ff-communication`.
```html
<ff-communication category-page="filterManufacturer=MyFilterString">
```
This attribute will set `navigation=true` and the specified filter string. The filter string will not be removable by `ff-asn-remove-all-filter`.
`add-params` will remain available and continue to be removable by `ff-asn-remove-all-filter`.

**Comment by omikron-fp** [comment]
`category-page` attribute was released a while ago.
