### ISSUE TITLE
"Products Per Page" (hitsPerPage) param is removed when using filter via ASN

### ISSUE THREAD

**Issue by tecbird** [FACT-Finder-Web-Components/ff-web-components#54]
Hi,

we are using current version 4.x of ff-web-components.
When we try to implement the "ff-record-list" + "ff-asn" + "ff-products-per-page-select" we got the described behavior.

If you first select hits per page to another value as default and then use any asn filter - the param "hitsPerPage" is removed / not kept,  so the default hits per page is applied.

This happend NOT if you load the hole page with param "hitsPerPage" existing in the url!
Seams to me that the asn filter links are not correct updated on the fly when you use "hitsPerPage" drodown without reloading page

**Comment by omikron-fp** [comment]
Hi @tecbird , thanks for reporting this issue.
We will schedule the fix for next week, and hopefully we will be able to release it by the end of next week.
I hope this is soon enough for you. If not, you might want to try to register a callback with `EventAggregator.addBeforeDispatchingCallback(event -> void)`, in the callback read the `hitsPerPage` value from `factfinder.communication.EventAggregator.currentSearchResult.searchParams`, and add it to the `event` object manually.

**Comment by tecbird** [comment]
thanks for the quick response! It's okay for us if it will be fixed next week. if not i will try to use the manuel workaround you described.

**Comment by omikron-fp** [comment]
Hi @tecbird, fix was release in [4.0.3](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/4.0.3).
Thanks for your patience.
